#!/usr/bin/env bash

#[ -t 1 ] &&


date

cardno=0

dirs=`ls -d1 /sys/class/drm/card*/device/pp_table | sort --version-sort` #natural sort for 10+ cards
if [[ -z $dirs ]]; then
        echo -e "No AMD GPUs found as /sys/class/drm/card*/device/pp_table"
        exit 1
fi

i=-1
for dir in $dirs; do
        (( i++ ))
        echo ""

        [[ $dir =~ \/card([0-9a-z]+)\/ ]]
        cardno=${BASH_REMATCH[1]}

        [[ -z $cardno ]] && echo -e "ERROR: can not match card no in $dir" && continue

      #  busid=`realpath /sys/class/drm/card$cardno/device | awk -F/ '{print $NF}'`
        busid=${busid#0000:} #trim prefix

        [[ -z $cardno ]] && echo -e "ERROR: can not match card no in $dir" && continue
        echo -e "=== GPU $i, $busid /sys/class/drm/card$cardno ==="


       # amdcovc -a $i

        #echo "  Performance level: `cat /sys/class/drm/card$cardno/device/power_dpm_force_performance_level`"
        #echo "  Core state: `cat /sys/class/drm/card$cardno/device/pp_dpm_sclk | grep '*'`"
        #echo "  Mem state: `cat /sys/class/drm/card$cardno/device/pp_dpm_mclk | grep '*'`"

        plevel=`cat /sys/class/drm/card$cardno/device/power_dpm_force_performance_level`
        [[ $plevel == "manual" ]] && plevelStr="$plevel" || plevelStr="$plevel"

        sclk=`cat /sys/class/drm/card$cardno/device/pp_dpm_sclk | grep -m1 '*'` #3: 1100Mhz *
        mclk=`cat /sys/class/drm/card$cardno/device/pp_dpm_mclk | grep -m1 '*'` #2: 1900Mhz *

        core_dpm=`echo $sclk | awk '{print $1}' | sed -e 's/://'`
        core_mhz=`echo $sclk | awk '{print $2}'`
        mem_dpm=`echo $mclk | awk '{print $1}' | sed -e 's/://'`
        mem_mhz=`echo $mclk | awk '{print $2}'`
       # corev=`wolfamdctrl -i $cardno --show-voltage | grep -m1 -A1 "Voltage state $core_dpm" | grep VDD | sed -E "s/.*VDD = (.*)/\1/"`


        pwr='n/a'
        [[ -e /sys/kernel/debug/dri/$cardno/amdgpu_pm_info ]] &&
                pwr=`cat /sys/kernel/debug/dri/$cardno/amdgpu_pm_info | grep -m1 '(average GPU)' | awk '{print $1}'`


        echo -e "$plevelStr \tDPM $core_dpm CORE $core_mhz MEM $mem_mhz \t\tPWR $pwr W"
done
